version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: BookSharing
    env_file:
      - .env
    environment:
      - MYSQL_HOST=${MYSQL_HOSTNAME}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '${MYSQL_PORT}:3306'

